# para versiones mas viejas de c++
CPPFLAGS=-std=c++2a

# para versiones mas nuevas de c++
#CPPFLAGS=-std=c++20

LDFLAGS=-pthread

.PHONY = all clean clase

all:  ej1-a ej1-b ej1-c ej1-d ej1-e ej2 ej2-alt ej3-a ej3-b ej3-c ej3-d
clean:
	rm -f ej1-a ej1-b ej1-c ej1-d ej1-e ej2 ej2-alt ej3-a ej3-b ej3-c ej3-d
